### PR TITLE
Fix edit command wrong suggestion

### LINKED ISSUE #113: Autocomplete not suggesting "/"  for tags
When autocompleting tags, (say n/) after the letter (n) has been typed out, autocomplete still visually suggests "n/" instead of just "/". This is just a visual bug, hitting tab still autocompletes just the slash. 

Image

### PR DESCRIPTION
**Pull request by Orange-eat97**
fixes #113 , #114 , #138, #142, #144

AutoComplete observes bad SOC and behaves errornously for suggeting "/" and early suggestion before index is present for "edit"

These reduces testability and affects user experience.

Let's fix it by creating seperate class to handle completing, ui display, and complete string creation.

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/AutoCompleteParser.java [hunk 1]
```diff
@@ -0,0 +1,122 @@
...
+
+    /**
+     * checks if string has sort
+     * @param text
+     * @return
+     */
+    public static boolean containsSort(String text) {
+        return text.contains(SortCommand.COMMAND_WORD);
+    }
+
```
Comment (EugeneOYZ1203n) [inline src/main/java/seedu/address/logic/parser/AutoCompleteParser.java]: These functions I know are created for SLAP but is isAddSort needed? its not even using the functions contains add and contains sort

**Review by EugeneOYZ1203n — APPROVED** [review]
Looks good, a simple implementation of my suggestion. 

Although there could be some OOP used, time limitations are tight so this gets the job done. 

Good job make such quick changes

**Comment by EugeneOYZ1203n** [comment]
Can consider adding test cases to these files
