### PR TITLE
Alpha bug fixes/command history

### LINKED ISSUE #116: Command history records repeated commands
Image

It appears that command history now records every command entered, regardless successfully executed or not. If a user mis-types many times, having too many lines of command history could be excessive.

Would it be better if we validate the input by checking there is no repeated lines stored in the command history first?

### LINKED ISSUE #117: Command history skipping latest command
Image
Command history skips the latest command executed when the command is executed successfully. As seen in the screenshot, the latest executed command was delete. As delete executes, command box becomes empty, and up-key returns the add command immediately before the delete command. 

I understand this fulfills our initial design, but would like to discuss whether this could be sub-optimal in such a scenerio: User added 2 people successfully, but the second add entry has a mistake. User would want to edit the second add command, while up-key returns the first add command.

I suppose this could be addressed by changing the return value? Or do you think returning the second last command would be more reasonable?

### PR DESCRIPTION
**Pull request by ruissouw**
Fixes #116

Fixes #117

### Fixes

- Solves #116 to an extent by not storing invalid commands.
- Solves #117 by retrieving the most recent command regardless of whether the UP or DOWN key is first pressed.

### Other things to take note

- Visually the command history now displays most recent command at the top and oldest at the bottom
- Only the latest 5 commands are stored in the command history
- When you are at the ends of the history, you go to the other extreme end (like a circular list)
- Added test cases for the string util methods I previously created
- Did some housekeeping by removing unnecessary methods in constructors

### CODE REVIEW

File: src/test/java/seedu/address/commons/util/StringUtilTest.java [hunk 1]
```diff
@@ -137,7 +157,152 @@ public void getDetails_exceptionGiven() {
...
+        );
+    }
+
+    @Test
+    public void getAllElements_onlySpaces_returnsEmptyArray() {
+        assertArrayEquals(new String[]{},
+                StringUtil.getAllElements("     ")
+        );
+    }
+
```
Comment (EugeneOYZ1203n) [inline src/test/java/seedu/address/commons/util/StringUtilTest.java]: Can you compress all these test cases into 1 or 2? I think this is really inefficient testing

**Review by EugeneOYZ1203n — APPROVED** [review]
LGTM
