### PR TITLE
Fix disordered params

### LINKED ISSUE #114: Autocomplete shows different tag while typing tag
When typing a certain tag (just the letter), another tag gets suggested by autocomplete. This is likely because you have pre-determined an order of precedence for the tag (presumably name being most important and so on and so forth). Fixing the other issue of suggesting just the "/" when typing a tag would likely solve this issue as well.

Image

### PR DESCRIPTION
**Pull request by Orange-eat97**
fixes #114 

AutoComplete forces param order when suggesting for param

Let's fix it so it suggests a "/" after valid param signatures.

### CODE REVIEW

File: src/main/java/seedu/address/ui/AutoCompleteSupplier.java [hunk 1]
```diff
@@ -92,10 +92,46 @@ public static String giveParam(String command, String text, List<String> params)
...
+        if (prefix == null) { //if prefix is null, keep it as a empty string for matching
+            prefix = "";
+        }
+
+        List<String> temp = getParamList(command);
+        String possibleParams = temp.stream().map(param -> param.substring(0, 1)).toString();
+
+        if (prefix.length() == 1 && suggestion.length() == 2 && suggestion.charAt(1) == '/'
+                && possibleParams.indexOf(prefix.charAt(0)) >= 0
+                && possibleParams.indexOf(suggestion.charAt(0)) >= 0) {
```
Comment (ruissouw) [inline src/main/java/seedu/address/ui/AutoCompleteSupplier.java]: Maybe can make helper methods for possibleParams.indexOf(prefix.charAt(0)) >= 0 and possibleParams.indexOf(suggestion.charAt(0)) >= 0 to improve code readability.

**Review by ruissouw — APPROVED** [review]
LGTM, good use of method overloading to distinguish autocompleting tags and commands
